# -*- coding: utf-8 -*-
"""Project108.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17t6mX1HgedTrh6ZoM_8GjOCol3Eje43z
"""

import plotly.figure_factory as ff
import pandas as pd
import random
import csv

df=pd.read_csv('data-Project108.csv')
fig=ff.create_distplot([df["Avg Rating"].tolist()],["Rating"],show_hist=True)
fig.show()